{% set name = "jupyter-rfb" %}
{% set version = "1.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace("-", "_") }}-{{ version }}.tar.gz
  sha256: b77a9a464e2da6d0b345b3989f037c4db2fc0c34da3379b380c42baeb0b3abca

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - flit-core >=3.2,<4
  run:
    - python
    - anywidget
    - numpy
    - simplejpeg

test:
  imports:
    - jupyter_rfb
  requires:
    - pip
    - anywidget
  commands:
    - pip check

about:
  home: https://github.com/vispy/jupyter_rfb
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Remote Frame Buffer for Jupyter
  description: |
    The jupyter_rfb library provides a widget (an anywidget subclass) that can be used
    in various notebook environments to implement a remote frame-buffer.
  dev_url: https://github.com/vispy/jupyter_rfb
  doc_url: https://jupyter-rfb.readthedocs.io

extra:
  recipe-maintainers:
    - kushalkolar
    - djhoese
    - almarklein
